// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides style recommendations for a jewelry item.
 *
 * - getStyleGuideSuggestions - A function that returns style suggestions for a given jewelry item.
 * - StyleGuideInput - The input type for the getStyleGuideSuggestions function.
 * - StyleGuideOutput - The return type for the getStyleGuideSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleGuideInputSchema = z.object({
  currentItemDescription: z
    .string()
    .describe('The description of the currently viewed jewelry item.'),
  availableProductsDescription: z
    .string()
    .describe('The description of the available products to recommend.'),
});
export type StyleGuideInput = z.infer<typeof StyleGuideInputSchema>;

const StyleGuideOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of suggested matching accessories.'),
});
export type StyleGuideOutput = z.infer<typeof StyleGuideOutputSchema>;

export async function getStyleGuideSuggestions(input: StyleGuideInput): Promise<StyleGuideOutput> {
  return styleGuideFlow(input);
}

const prompt = ai.definePrompt({
  name: 'styleGuidePrompt',
  input: {schema: StyleGuideInputSchema},
  output: {schema: StyleGuideOutputSchema},
  prompt: `You are a personal jewelry stylist. Given a description of the currently viewed item, and a description of available products, recommend up to 3 accessories that would complement the viewed item. The accessories should be of similar style and aesthetic.

Viewed Item Description: {{{currentItemDescription}}}
Available Products Description: {{{availableProductsDescription}}}

Suggestions:`,
});

const styleGuideFlow = ai.defineFlow(
  {
    name: 'styleGuideFlow',
    inputSchema: StyleGuideInputSchema,
    outputSchema: StyleGuideOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
